import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import RQProvider from '@/lib/RQProvider';
import Header from './_components/Header';
import AuthSession from '@/lib/SessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <AuthSession>
          <Header />
          <RQProvider>
            <StyledComponentsRegistry>
              {children}
              {auth}
            </StyledComponentsRegistry>
          </RQProvider>
        </AuthSession>
      </body>
    </html>
  );
}
