import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import RQProvider from '@/lib/RQProvider';
import Header from './_components/Header';
import AuthSession from '@/lib/SessionProvider';
import MobileHeader from './_components/MobileHeader';

const pretendard = localFont({
  src: '../styles/font/PretendardVariable.ttf',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <AuthSession>
          <Header />
          <MobileHeader />
          <RQProvider>
            <StyledComponentsRegistry>
              {children}
              {auth}
            </StyledComponentsRegistry>
          </RQProvider>
        </AuthSession>
      </body>
    </html>
  );
}
